// default package
// Generated May 30, 2018 6:48:12 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

	private Long userid;
	private String name;

	public User() {
	}

	public User(String name) {
		this.name = name;
	}

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
